"""Requirement traceability: which test (or campaign check) verifies which requirement.

Tests declare what they verify with a decorator:

    from aeris.trace import verifies

    class TestGps(unittest.TestCase):
        @verifies("AERIS-REQ-FDIR-001")
        def test_stale_gps_declared_quickly(self): ...

`python -m aeris trace --check` collects these tags, writes docs/trace_matrix.md and
fails if any requirement in docs/requirements.json has nothing verifying it.
"""
import json
import unittest
from pathlib import Path

CAMPAIGN_CHECKED = {"AERIS-REQ-FDIR-001", "AERIS-REQ-FDIR-003", "AERIS-REQ-FDIR-004", "AERIS-REQ-SYS-001"}


def verifies(*requirement_ids):
    def mark(fn):
        fn.requirements = tuple(requirement_ids)
        return fn
    return mark


def _iter_tests(suite):
    for item in suite:
        if isinstance(item, unittest.TestSuite):
            yield from _iter_tests(item)
        else:
            yield item


def collect(root):
    suite = unittest.defaultTestLoader.discover(str(Path(root) / "tests"), top_level_dir=str(root))
    found = {}
    for test in _iter_tests(suite):
        method = getattr(test, test._testMethodName, None)
        for rid in getattr(method, "requirements", ()):
            found.setdefault(rid, []).append(f"{type(test).__module__}.{type(test).__name__}.{test._testMethodName}")
    return found


def build_trace(root):
    reqs = json.loads((Path(root) / "docs" / "requirements.json").read_text(encoding="utf-8"))
    tests = collect(root)
    lines = ["# Requirement trace matrix", "",
             "Generated by `python -m aeris trace`. Do not edit by hand.", "",
             "| Requirement | Hazard | Verification | Verified by |", "|---|---|---|---|"]
    ok = True
    for r in reqs["requirements"]:
        by = [f"`{t}`" for t in tests.get(r["id"], [])]
        if r["id"] in CAMPAIGN_CHECKED:
            by.append("campaign check (`python -m aeris campaign`)")
        if not by:
            ok = False
            by = ["**NOT VERIFIED**"]
        lines.append(f"| **{r['id']}**<br>{r['text']} | {', '.join(r.get('hazards', []))} | "
                     f"{r['verification']} | {'<br>'.join(by)} |")
    lines += ["", "## Hazards", "", "| ID | Hazard | Worst credible effect |", "|---|---|---|"]
    for h in reqs["hazards"]:
        lines.append(f"| {h['id']} | {h['hazard']} | {h['effect']} |")
    return ok, "\n".join(lines) + "\n"
